# This file stores configurations for your Shopify app.
name = "Captain Caskwell Affiliate"
client_id = "bfcda3eea412348564908c00925a435d"
application_url = "https://bottle-nexus-affiliate-app.fly.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_publications,write_publications,read_content,write_content,read_online_store_pages,write_online_store_pages,read_themes,write_themes,read_inventory,write_inventory,read_locations,read_legal_policies,write_legal_policies"

[auth]
redirect_urls = [
  "https://bottle-nexus-affiliate-app.fly.dev/auth/callback",
]

[webhooks]
api_version = "2025-10"

  # Handled by: /app/routes/webhooks.app.uninstalled.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  # Handled by: /app/routes/webhooks.app.scopes_update.tsx
  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  # Webhooks can have filters
  # Only receive webhooks for product updates with a product price >= 10.00
  # See: https://shopify.dev/docs/apps/build/webhooks/customize/filters
  # [[webhooks.subscriptions]]
  # topics = ["products/update"]
  # uri = "/webhooks/products/update"
  # filter = "variants.price:>=10.00"

  # Mandatory compliance topics for public apps.
  # Handled by: /app/routes/webhooks.compliance.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
